overwrite: true
schema: src/graphql/generated/schema.json
documents: 'src/**/*.graphql'
generates:
  src/graphql/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - fragment-matcher
    config:
      withHooks: true
      withComponent: false
      withHOC: false
config:
  scalars:
    ID: string
hooks:
  afterAllFileWrite:
    - prettier --write
    - eslint -c config/.eslintrc.js --fix
